"""
Defines the state schema for the application.

Three-entity workflow:
- Customer: Initiates the process by submitting a support ticket
- Assistant: Processes ticket, classifies issue, fetches order, drafts reply recommendation
- Admin: Reviews assistant's recommendation and approves/rejects it
"""
from typing import TypedDict, List, Optional, Dict, Any, Literal
from langchain_core.messages import BaseMessage


# Status types for the workflow
StatusType = Literal["pending", "awaiting_admin", "approved", "rejected", "completed"]


class GraphState(TypedDict):
    """
    State schema for the LangGraph workflow with three-entity support.
    
    This TypedDict defines the structure of the state that flows through
    the graph, supporting customer -> assistant -> admin workflow.
    
    Attributes:
        messages: List of message objects for conversation history.
            Uses LangChain's BaseMessage for compatibility with LangGraph.
        ticket_text: The original ticket text submitted by the customer.
        order_id: The order ID extracted from the ticket or provided explicitly.
            None if no order ID is found or relevant.
        issue_type: The classified type of issue (e.g., "refund_request",
            "late_delivery", "damaged_item", etc.). None if not yet classified.
        evidence: Additional evidence or context collected during processing.
            Contains relevant information gathered from external sources or
            ticket analysis. May include policy_citations and policy_justification
            from the policy RAG flow. None if no additional evidence has been collected.
        recommendation: The drafted reply recommendation generated by the assistant.
            None if the recommendation has not yet been generated.
        status: Current workflow status tracking the three-entity flow.
            - "pending": Initial state, customer submitted ticket
            - "awaiting_admin": Assistant has drafted recommendation, waiting for admin
            - "approved": Admin approved the recommendation
            - "rejected": Admin rejected the recommendation
            - "completed": Workflow completed
        admin_decision: Admin's decision on the recommendation ("approve" or "reject").
        admin_feedback: Optional feedback from admin explaining their decision.
    """
    messages: List[BaseMessage]
    ticket_text: str
    order_id: Optional[str]
    issue_type: Optional[str]
    evidence: Optional[Dict[str, Any]]
    recommendation: Optional[str]
    status: Optional[str]
    admin_decision: Optional[str]
    admin_feedback: Optional[str]
    refund_preview: Optional[Dict[str, Any]]
